### ISSUE TITLE
Can you please add the following as contributors?

### ISSUE THREAD

**Issue by kakiac** [AlexanderJohnRobertson/devops-uos#3]
Git hub usernames below:

kakiac
S275283
farhatuos
thom-jacobs
MTalha095

New:
S272833
S274527
gpdzvapatsva

**Comment by farhatuos** [comment]
here is mine: farhatuos

**Comment by gpdzvapatsva** [comment]
Add me too : gpdzvapatsva

**Comment by AlexanderJohnRobertson** [comment]
Closing
